#!/bin/bash
#SBATCH -N 1      # nodes requested
#SBATCH --time=01:00:00
#SBATCH --gres=gpu:1
#SBATCH --qos=short
#SBATCH --output=/slurm-storage/linbao/thesis_code_1/outputs/%x_%j.out   # standard output
#SBATCH --error=/slurm-storage/linbao/thesis_code_1/outputs/%x_%j.err    # standard error

echo "/slurm-storage/linbao/thesis_code_1/GRIT/configs/HomBias/testing/OG-test.yaml"
srun -u /slurm-storage/linbao/.conda/envs/GPS-envV5/bin/python "/slurm-storage/linbao/thesis_code_1/GRIT/main.py" --cfg "/slurm-storage/linbao/thesis_code_1/GRIT/configs/HomBias/testing/OG-test.yaml" --repeat 1 wandb.use True
